name: Simple Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Build and push
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-ml-app:latest .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-ml-app:latest
        
    - name: Deploy to VM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 74.234.179.93
        username: ubuntu
        password: Supermotdepasse!42
        script: |
          docker stop fastapi-ml-app || true
          docker rm fastapi-ml-app || true
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-ml-app:latest
          docker run -d --name fastapi-ml-app -p 6670:6670 --restart unless-stopped ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-ml-app:latest 