name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest httpx
        
    - name: Test API endpoints
      run: |
        python -c "
        import fastapi
        from fastapi.testclient import TestClient
        import sys
        sys.path.append('.')
        from fast_api import app
        
        client = TestClient(app)
        
        # Test root endpoint
        response = client.get('/')
        assert response.status_code == 200
        print('✅ Root endpoint test passed')
        
        # Test prediction endpoint
        response = client.post('/predict?size=180&nb_rooms=3&garden=true')
        assert response.status_code == 200
        assert 'y_pred' in response.json()
        print('✅ Prediction endpoint test passed')
        
        print('All tests passed successfully!')
        "
        
    - name: Validate Docker build
      run: |
        docker build -t test-image .
        echo "✅ Docker build successful" 